export const dashInfo = [
    {
        title:'Students',
        icon:'/assets/icons/bookmark-student.svg',
        detail:'19',
        bgColor:'#F0F9FF',
        textColor:'#6C6C6C'
    },
    {
        title:'Lessons',
        icon:'/assets/icons/bookmark-course.svg',
        detail:'4',
        bgColor:'#FEF6FB',
        textColor:'#6C6C6C'
    },
    {
        title:'Payments',
        icon:'/assets/icons/bookmark-payment.svg', 
        detail:'15,600',
        currency:'₺',
        bgColor:'#FEFBEC',
        textColor:'#6C6C6C'
    },
    {
        title:'Teachers',
        icon:'/assets/icons/bookmark-user.svg',
        detail:'2',
        bgColor:' linear-gradient(to right, #FEAF00, #F8D442)',
        textColor:'#fff'
    }
]